### ISSUE TITLE
[Nyiur Theme] Youtube video in the reply of an ask breaks out of the post. 

### ISSUE THREAD

**Issue by Just-a-Space-Rabbit** [fukuo-themes/tumblr-theme#37]
![bilde](https://github.com/user-attachments/assets/1480acfe-87c7-470e-b9f5-afbc7cece76c)

**Comment by fukou** [comment]
Hi @Just-a-Space-Rabbit 

Thank you for informing me about the issue.

Since it takes time for the theme updates to be approved by Tumblr staff, would you mind pasting this CSS code below on your customization page?

```CSS
.tmblr-embed.tmblr-full > iframe {
  width: 100%;
  height: 100%;
  aspect-ratio: 16/9;
  margin: 1rem 0;
  border-radius: 8px;
}
```

Here's the step-by-step:
- Go to your customize page, https://tumblr.com/customize/just-a-space-rabbit
- Scroll down until you find "Advanced Options"
- Click that and add the CSS above under the "Add Custom CSS"
- Click the "Save" blue button and you're done!

Let me know if you have anything else!
Thank you.
